parameter_defaults:
  CephPoolDefaultSize: 3
  CephPoolDefaultPgNum: 64
  # python bug
  CephAnsiblePlaybookVerbosity: 0
  CephAnsibleEnvironmentVariables:
    ANSIBLE_SSH_RETRIES: '6'
  CephAnsibleDiskConfig:
    devices:
      - /dev/vdb
      - /dev/vdc
    osd_scenario: lvm
    osd_objectstore: bluestore
  CephConfigOverrides:
    mon_clock_drift_allowed: 0.5
    osd_pool_default_min_size: 1
    mon_pg_warn_min_per_osd: 0
    mon_pg_warn_max_per_osd: 0
    mon_pg_warn_max_object_skew: 0
    mon_max_pg_per_osd: 1024
    #mon_osd_allow_primary_affinity: 1
    rgw_enable_usage_log: false
  CephAnsibleExtraConfig:
    osd_recovery_op_priority: 1
    osd_recovery_max_active: 1
    osd_max_backfills: 1
    #journal_size: 40960
    # Avoid timeout of podman pulling rhceph image from undercloud
    docker_pull_timeout: "600s"
  #CephStorageImage: overcloud-minimal
  # Dashboard does not work yet
  #CephEnableDashboard: True
  #CephDashboardAdminPassword: redhat

